data:
  train_files: hiyouga/math12k@train
  val_files: hiyouga/math12k@test
  prompt_key: problem
  answer_key: answers
  image_key: images
  video_key: videos
  image_dir: null
  video_fps: 1.0
  max_prompt_length: 4096
  max_response_length: 1024
  rollout_batch_size: 4  #  to verl's data.train_batch_size
  mini_rollout_batch_size: null  # equivalent to verl's data.gen_batch_size
  val_batch_size: 4
  format_prompt: ./examples/format_prompt/math.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  min_pixels: 262144
  max_pixels: 4194304
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  online_filtering: false  # dapo filter groups
  filter_key: overall
  filter_low: 0.01
  filter_high: 0.99

worker:
  actor:
    global_batch_size: 1  # equivalent to verl's actor.ppo_mini_batch_size
    micro_batch_size_per_device_for_update: 2  # equivalent to verl's actor.ppo_micro_batch_size_per_gpu
    micro_batch_size_per_device_for_experience: 8  # equivalent to verl's rollout.log_prob_micro_batch_size_per_gpu
    max_grad_norm: 1.0
    padding_free: true
    ulysses_size: 1
    model:
      model_path: Qwen/Qwen2.5-3B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      override_config:
        torch_dtype: "bfloat16"           # 确保权重以 bf16 加载
        attn_implementation: "flash_attention_2"
      use_lora: true         # 开启LoRA
      lora_r: 16              # LoRA秩
      lora_alpha: 32         # LoRA α
      lora_dropout: 0.1      # LoRA dropout
      lora_target_modules: ["q_proj","v_proj","lm_head","visual.proj"]
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
      torch_dtype: bf16  # 确保权重以 bf16 加载
      # mp_param_dtype: bf16        # 参数主副本 dtype
      # mp_buffer_dtype: bf16       # buffer dtype
      # mp_reduce_dtype: bf16       # grad reduce dtype

    offload:
      offload_params: false  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 16
    temperature: 1.0
    top_p: 0.99
    limit_images: 0
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    disable_tqdm: false
    val_override_config:
      temperature: 0.5
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
      torch_dtype: bf16
      # mp_param_dtype: bf16
      # mp_buffer_dtype: bf16
      # mp_reduce_dtype: bf16
    offload:
      offload_params: false

  reward:
    reward_type: batch
    reward_function: ./examples/reward_function/math.py:compute_score

trainer:
  total_epochs: 1
  max_steps: null
  project_name: easy_r1
  experiment_name: qwen2_5_7b_math_grpo
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 8
  max_try_make_batch: 20  # -1 means no limit
  val_freq: 1  # -1 to disable
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 1  # -1 to disable
  save_limit: 2  # -1 to disable
  save_model_only: false
  save_checkpoint_path: /root/autodl-tmp/home/lizhuohang/reaserch/ICLR2026/EasyR1/saves/lora
  load_checkpoint_path: null
